export const FETCH_STOCK_ITEM_SUCCESS = 'FETCH_STOCK_ITEM_SUCCESS';
export const FETCH_STOCK_ITEM_FAILURE = 'FETCH_STOCK_ITEM_FAILURE';
export const FETCH_STOCK_ITEM_REQUEST = 'FETCH_STOCK_ITEM_REQUEST';
